### ISSUE TITLE
default config file error  ?

### ISSUE THREAD

**Issue by HumanG33k** [chaica/retweet#10]
No option 'waitminsecs' in section: 'main' when i try to launch 
#retweet /pathTo/config.ini

i use a copy / modify file from http://retweet.readthedocs.io/en/latest/configure.html
and no process retweet when i 
#ps auxf|grep  "*retweet*"

sys info
Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

the log for the install 

#python3.4 setup.py install --install-scripts=/usr/bin
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3.4 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating retweet.egg-info
writing retweet.egg-info/PKG-INFO
writing requirements to retweet.egg-info/requires.txt
writing top-level names to retweet.egg-info/top_level.txt
writing dependency_links to retweet.egg-info/dependency_links.txt
writing manifest file 'retweet.egg-info/SOURCES.txt'
reading manifest file 'retweet.egg-info/SOURCES.txt'
writing manifest file 'retweet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/retweet
copying retweet/confparse.py -> build/lib/retweet
copying retweet/tweetwasposted.py -> build/lib/retweet
copying retweet/cliparse.py -> build/lib/retweet
copying retweet/main.py -> build/lib/retweet
copying retweet/senttweets.py -> build/lib/retweet
copying retweet/validate.py -> build/lib/retweet
copying retweet/waitamoment.py -> build/lib/retweet
copying retweet/__init__.py -> build/lib/retweet
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/retweet
copying build/lib/retweet/confparse.py -> build/bdist.linux-x86_64/egg/retweet
copying build/lib/retweet/tweetwasposted.py -> build/bdist.linux-x86_64/egg/retweet
copying build/lib/retweet/cliparse.py -> build/bdist.linux-x86_64/egg/retweet
copying build/lib/retweet/main.py -> build/bdist.linux-x86_64/egg/retweet
copying build/lib/retweet/senttweets.py -> build/bdist.linux-x86_64/egg/retweet
copying build/lib/retweet/validate.py -> build/bdist.linux-x86_64/egg/retweet
copying build/lib/retweet/waitamoment.py -> build/bdist.linux-x86_64/egg/retweet
copying build/lib/retweet/__init__.py -> build/bdist.linux-x86_64/egg/retweet
byte-compiling build/bdist.linux-x86_64/egg/retweet/confparse.py to confparse.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/retweet/tweetwasposted.py to tweetwasposted.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/retweet/cliparse.py to cliparse.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/retweet/main.py to main.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/retweet/senttweets.py to senttweets.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/retweet/validate.py to validate.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/retweet/waitamoment.py to waitamoment.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/retweet/__init__.py to __init__.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.4
copying and adjusting scripts/retweet -> build/scripts-3.4
changing mode of build/scripts-3.4/retweet from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.4/retweet -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/retweet to 755
copying retweet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying retweet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying retweet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying retweet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying retweet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/retweet-0.8-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing retweet-0.8-py3.4.egg
Copying retweet-0.8-py3.4.egg to /usr/local/lib/python3.4/dist-packages
Removing retweet 0.6 from easy-install.pth file
Adding retweet 0.8 to easy-install.pth file
Installing retweet script to /usr/bin

Installed /usr/local/lib/python3.4/dist-packages/retweet-0.8-py3.4.egg
Processing dependencies for retweet==0.8
Searching for SQLAlchemy==1.0.10
Best match: SQLAlchemy 1.0.10
Processing SQLAlchemy-1.0.10-py3.4.egg
SQLAlchemy 1.0.10 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.10-py3.4.egg
Searching for tweepy==3.5.0
Best match: tweepy 3.5.0
Processing tweepy-3.5.0-py3.4.egg
tweepy 3.5.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/tweepy-3.5.0-py3.4.egg
Searching for six==1.8.0
Best match: six 1.8.0
six 1.8.0 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Searching for requests-oauthlib==0.6.0
Best match: requests-oauthlib 0.6.0
Processing requests_oauthlib-0.6.0-py3.4.egg
requests-oauthlib 0.6.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/requests_oauthlib-0.6.0-py3.4.egg
Searching for requests==2.4.3
Best match: requests 2.4.3
requests 2.4.3 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Searching for oauthlib==1.0.3
Best match: oauthlib 1.0.3
Processing oauthlib-1.0.3-py3.4.egg
oauthlib 1.0.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/oauthlib-1.0.3-py3.4.egg
Finished processing dependencies for retweet==0.8

**Comment by chaica** [comment]
thanks for the report. A default value is missing for waitminsecs and waitmaxsecs if you don't use them in the ini file. I'll fix it by hardcoding default values in the code.

**Comment by HumanG33k** [comment]
Maybe you should add a complete list of option for the ini file and update the documentation, and instead of hardcoding use a /etc/retweet/default.ini parse it and replace if needed by command line file. A great feature can be look for conf file somewhere in ~/.config/retweet/etc ?

**Comment by chaica** [comment]
Yes, I'll think about a complete list of optiions.
Nonetheless you need a default value for these options because they are mandatory, could be removed accidentally from the ini file by the user and this error message is quite unclear, especially for new user.

**Comment by chaica** [comment]
solved by release 0.9
