### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by sbmueller** [chaica/retweet#2]
Hey, I am having trouble running this tool. This is the console output:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/retweet", line 24, in <module>
    Main()
  File "/usr/local/lib/python3.4/dist-packages/retweet/main.py", line 47, in __init__
    self.main()
  File "/usr/local/lib/python3.4/dist-packages/retweet/main.py", line 62, in main
    lasttweetid = lasttweets[-1].id
IndexError: list index out of range
```
Any idea what causes this error?

**Comment by chaica** [comment]
Sorry for the delay but I didn't receive the notification email for this bug report! I'll have a look at it and keep you informed.

Regards,
Carl

**Comment by chaica** [comment]
question: do you have a lastsenttweetid file and if so, could you show me the content of this file?

**Comment by sbmueller** [comment]
Thank you for investigating! At first I just installed your application using pip. When I follow your readme instructions, this error occurs. I also tried to create an empty file `lasttweetid` but with no success.

**Comment by sbmueller** [comment]
I have now written the number 1 in the file. Now it works. Maybe you should update your documentation to inform other users that a non-empty lasttweetid file is needed :)
