### ISSUE TITLE
(for first-time contributor) Nice command line management with argparse

### ISSUE THREAD

**Issue by chaica** [chaica/retweet#5]
The goal of this bug report is to write a nice commande-line management using argparse for retweet. This bug report should be studied  by a first-time contributor to a free or opensource software. It should lead to a Github Pull Request in order to solve this bug report.

1/ In your Github , fork the repository retweet
2/ in the retweet module (the retweet directory in the root directory) , create a CliParse class . It should have a init , a main() and an attribute cliargs (have a look at the structure of retweet/cliparse.py and organize you code the same way, it's pretty simple)
3/ write the unit test to check if your CliParse class works
4/ in main.py , you should instantiate CliParse before other objects, get the attribute cliargs
5/ modify the ConfParse class in order ConfParse knows what configuration file it must parse
6/ In your Github generate a Pull Request

I'll be available if you have any question.

Regards,
Carl

**Comment by Charlotteis** [comment]
Hello! Thanks so much for writing this issue and offering your help. I thought I'd let you know I'll be tweeting about this next week from the Your First PR twitter account (http://twitter.com/yourfirstpr) which links to great issues for first timers. Thanks again ✨

**Comment by chaica** [comment]
done by myself, sorry guys ;)
