### ISSUE TITLE
No module named 'setuptools'

### ISSUE THREAD

**Issue by HumanG33k** [chaica/retweet#7]
When i try to install it from source according to https://retweet.readthedocs.org/en/latest/install.html
I have this message : 

Traceback (most recent call last):   File "setup.py", line 21, in <module>     from setuptools import setup ImportError: No module named 'setuptools'

The install script 
# cat retweet_install 
#!/bin/bash
wget https://github.com/chaica/retweet/archive/0.6.tar.gz &&tar zxvf 0.6.tar.gz && cd retweet-0.6/ && python3.4 setup.py install --install-scripts=/usr/bin

I'm on debian stable. python3.4 and python-setuptools install(even if not identified has requirement in the doc )

**Comment by chaica** [comment]
Hi,

On Debian you need the debian package python3-setuptools. Let me know if it solves your issue.

Regards,
Carl Chenet

**Comment by chaica** [comment]
Guess it was solved in 0.6 with new doc by #8 . Let me know by reopening if necessary
